# .github/workflows/release.yml
name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write # Grant permissions for release creation

jobs:
  release:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x # minor バージョン固定

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Build and Publish
        run: |
          dotnet publish ./src/DisplayRotator.csproj --configuration Release --runtime win-x64 --self-contained false -p:PublishSingleFile=false -p:PublishReadyToRun=true --output publish -v minimal

      - name: Verify Publish Directory
        run: |
          echo "Listing contents of publish directory:"
          ls -R publish

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: DisplayRotator-Build
          path: publish/**

      - name: Zip Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: "zip"
          filename: "DisplayRotator-${{ github.ref_name }}.zip"
          directory: "publish"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: "**/DisplayRotator-${{ github.ref_name }}.zip"
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
